### ISSUE TITLE
[URGENT] Unable to train

### ISSUE THREAD

**Issue by nitishgupta** [eladsegal/tag-based-multi-span-extraction#1]
I am getting an error in trying to train the model -- During the dataset reading phase I get the error `sre_constants.error: bad escape \p at position 257`

Looking at the code it looks like you perform some data cleaning. What are the commands to do that?

**Comment by eladsegal** [comment]
Looks like it is not related to our code: https://github.com/explosion/spaCy/issues/3544, https://github.com/explosion/spaCy/issues/4261.

As for the data cleaning, there are two parts we considered as such and they are both configurable in the config file:
- Unrelated to the reader: We used `data_cleaning/ner_cleaning.py` to generate `data/drop_dataset_train_clean.json` which has some of the multi-span answers modified.
- In the reader: There's the `standardize_texts` flag which replaces HTML character references to Unicode characters.

**Comment by nitishgupta** [comment]
I'm so sorry about that. I should have read the logs clearly. I will try the solution you mentioned.

**Comment by eladsegal** [comment]
No need to apologize :) 
Feel free to ask any question, we'd be happy to help!
