### ISSUE TITLE
TASE_IO pretrained model link not working

### ISSUE THREAD

**Issue by carolmanderson** [eladsegal/tag-based-multi-span-extraction#12]
Hi, I'd like to try out your pretrained TASE_IO model for comparison with TASE_IO + SSE. I saw that you kindly shared the model last year in issue #4, but the Google Drive link isn't working. Would you be willing & able to share that again?

**Comment by eladsegal** [comment]
Hi, sure!
I added it at the bottom of the README.

**Comment by carolmanderson** [comment]
Thank you!
