### ISSUE TITLE
Error during pip

### ISSUE THREAD

**Issue by cy716** [eladsegal/tag-based-multi-span-extraction#13]
Hi Elad, I am trying to reproduce your paper.
`pip install -r requirements.txt  `fails, generating the following warning and error:
```
Collecting allennlp
  Cloning git://github.com/eladsegal/allennlp (to revision 2143c7c) to /tmp/pip-install-ypvlqx77/allennlp
ERROR: Command errored out with exit status 128: git clone -q git://github.com/eladsegal/allennlp /tmp/pip-install-ypvlqx77/allennlp Check the logs for full command output.
```
Thanks for your help~

**Comment by eladsegal** [comment]
Hi, this was an issue caused by an update to the Git protocol.
I updated the requirements file to use http, it should work now.

**Comment by cy716** [comment]
> Hi, this was an issue caused by an update to the Git protocol.
> I updated the requirements file to use http, it should work now.

Thanks a lot!

**Comment by fanruiwen** [comment]
Hello,I meet this issue too,and it can not work now.

**Comment by eladsegal** [comment]
Hi, can you please share the pip version you use and the error you get?

**Comment by cy716** [comment]
I have tried it again and it doesn’t work either. Maybe you can ask the author for the solution. Sorry not to be able to help.

**Comment by cy716** [comment]
> Hello,I meet this issue too,and it can not work now.

I have tried it again and it doesn’t work either. Maybe you can ask the author for the solution. Sorry not to be able to help.
