### ISSUE TITLE
allennlp is avaiable but the tag 2143c7c is unavailable

### ISSUE THREAD

**Issue by aoko920** [eladsegal/tag-based-multi-span-extraction#15]
WARNING: Discarding git+https://github.com/eladsegal/allennlp@2143c7c#egg=allennlp. Command errored out with exit status 1: 'D:\Coding\Python\anaconda\envs\pytorch\python.exe' 'D:\Coding\Python\anaconda\envs\pytorch\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Ray\AppData\Local\Temp\pip-build-env-96i0oiup\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i http://pypi.douban.com/simple --trusted-host pypi.douban.com -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement allennlp (unavailable)
ERROR: No matching distribution found for allennlp (unavailable)

**Comment by eladsegal** [comment]
Which pip version are you using?
Installation runs smoothly for me with  pip 21.2.4

**Comment by aoko920** [comment]
> Which pip version are you using? Installation runs smoothly for me with pip 21.2.4

pip 22.1.2 (python 3.9)
P.S. I click directly on this URL, it says "page not found"

**Comment by eladsegal** [comment]
The link is not accessible through the browser, so that's ok.
I tried using the same pip version, but I can't reproduce the issue.
Can you post the log so I'll see the full command output?

**Comment by junzai0215** [comment]
> > Which pip version are you using? Installation runs smoothly for me with pip 21.2.4
> 
> pip 22.1.2 (python 3.9) P.S. I click directly on this URL, it says "page not found"

Have you solved this problem?  I meet the same problem. Please tell me the solution, thank you very much!
