### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by nitishgupta** [eladsegal/tag-based-multi-span-extraction#2]
This error popped up after 1 epoch of training

```
 File "./src/nabertplusplus/nabertplusplus.py", line 376, in forward
    best_answer_ability[i] = top_two_answer_abilities.indices[i][1]
AttributeError: 'tuple' object has no attribute 'indices
```

**Comment by eladsegal** [comment]
Can you please include the training command you used and the configuration file (if it is not one of the configurations in the repo)?

**Comment by eladsegal** [comment]
The problem is that before pytorch 1.1.0 `topk` (which is used for `top_two_answer_abilities`) returned a tuple, but starting from 1.1.0 it returns a namedtuple.
I'll update requirements.txt  accordingly.
