### ISSUE TITLE
How to get model.tar.gz

### ISSUE THREAD

**Issue by vincentlux** [eladsegal/tag-based-multi-span-extraction#4]
Hi, thank you very much for open source the project! I am trying to reproduce the results. May I ask if you can release the model.tar.gz for inference and try the model? Or could you point me to how to train and get that model? Thanks a lot for your help!

**Comment by vincentlux** [comment]
I got it, thanks!

**Comment by eladsegal** [comment]
Hi, thank you for your interest! I am glad you got it.
I don't have a permanent large storage available, but I can upload any of the models included in the paper to a temporary storage. Let me know if you do want me to upload some of them.

**Comment by vincentlux** [comment]
Hi Elad, thanks a lot for your help! I really appreciate it. 
If it is possible, could you share the TASE-IO model.tar.gz and TASE-IO+SSE model.tar.gz trained on DROP data? I want to try these two models and see how they perform in the single-span and multi-span scenario. Thanks!

**Comment by eladsegal** [comment]
Hi Xiaopeng, I'm happy to help.
Looks like the TASE_IO + SSE was inadvertently deleted, so I'm sharing the BIO version instead.

Here are the links:
TASE_IO - https://drive.google.com/file/d/1-Km5THXNpd38Pyat9o0FSNL6gfS3pTV1/view?usp=sharing
TASE_BIO + SSE - https://drive.google.com/file/d/1R_p1YaeuJ_SQOHLNdpJTkjUrfLlAb44A/view?usp=sharing

**Comment by vincentlux** [comment]
Hi Elad, I just downloaded it. Thank you very much for sharing!

**Comment by kiet13** [comment]
Hi, Elad. I am looking for the file model.tar.gz to try the model but these 2 download links above do not exist. Could you provide other links?

**Comment by eladsegal** [comment]
Hi Nguyen, I found the TASE_IO + SSE model.
https://drive.google.com/file/d/1k8MFEmmGeUXlBmghAKN8Xl_a6mbFUHdn/view

If you want other models too, let me know.

**Comment by kiet13** [comment]
I just downloaded it. Thank you for sharing
