### ISSUE TITLE
Use .th files for multi-step training

### ISSUE THREAD

**Issue by liuzzom** [eladsegal/tag-based-multi-span-extraction#7]
Hi.
I would like to use a .th file created during training, but I can't see if there is an istruction to do this.
Is it possible to do this? If yes, how can I do?

Thanks to everyone

**Comment by eladsegal** [comment]
You can use `model_state_epoch_*.th`, but you need to create a `.tar.gz` file from it first with https://github.com/allenai/allennlp/blob/main/allennlp/models/archival.py#L107.

**Comment by liuzzom** [comment]
Hi.
The `tar.gz` is the same that the model creates on every epoch during training?

**Comment by eladsegal** [comment]
Not every epoch, just at the end of the training, or when you stop the training after at least one epoch has been completed.

**Comment by liuzzom** [comment]
Hi.
I see that the model save a `.th` file for every epoch and that these are not deleted after the completion of the next epoch (e.g. `model_state_epoch_0`.th is not deleted after the train on epoch 2 or 3, ecc...). 

Since I have space requirements. is it possible to delete older `.th` files without creating problems?

**Comment by eladsegal** [comment]
Yes, you can add `num_serialized_models_to_keep` here:
https://github.com/eladsegal/tag-based-multi-span-extraction/blob/d8619f49d5e160c40e6223860040a6ba79bbc612/configs/abstract/model.jsonnet#L124-L136

See documentation here:
https://github.com/eladsegal/allennlp/blob/f7fa29ce68f8c6a1d7eacf5fc2190895d5cab2fc/allennlp/training/trainer.py#L112-L117

**Comment by liuzzom** [comment]
Thanks
