### ISSUE TITLE
Get ^C interrupt using allennlp train with --recover

### ISSUE THREAD

**Issue by liuzzom** [eladsegal/tag-based-multi-span-extraction#8]
Hi.
I'm trying to run the code on a Google Colab notebook. I interrupted the training after 2 epochs using the Colab command for interrupting the execution.
When I try to run again the `train` command using the `--recover` option, the execution stops after the load of the model (model information are printed in the output). The last output row contains only `^C`

[here](https://pastebin.com/sThTZU7K) you can find the cell execution output

Thanks to everyone

**UPDATE**: The same thing happens also when I train the model on one epoch (and not 35 as in the original configuration)

**Comment by eladsegal** [comment]
Sorry, I can't help you with that. Looks like it is an issue with colab and allennlp and not with our code.

**Comment by liuzzom** [comment]
Thanks.

**UPDATE**: the reason for the interrupt is Colab because the amount of RAM of a standard notebook is not enough to the recovery process.
