### ISSUE TITLE
[Paper Doubt] Annotation Meaning.

### ISSUE THREAD

**Issue by WatsonWangZh** [eladsegal/tag-based-multi-span-extraction#9]
What's the difference between TASEBIO + SSE and TASEBIO+SSE(BERTLARGE)? is it ROBERTALARGE?

**Comment by liuzzom** [comment]
Hi.
I'm currently trying to train the model. I think that the TASEBIO+SSE uses RoBERTa, while TASEBIO+SSE(BERTLARGE) uses the standard BERT.

I'll edit this comment if I get some updates

**Comment by eladsegal** [comment]
@liuzzom is correct.
Our models use RoBERTa large by default (see Section 5), so it is not mentioned explicitly in the configuration. 
The usage of BERT large was for a fair comparison with previous work.
